export type PromptUsageStatus = 'database' | 'fallback' | 'inline'

export interface PromptUsageItem {
  id: string
  category: string
  feature: string
  stage: string
  promptNames: string[]
  fallbackPromptNames?: string[]
  status: PromptUsageStatus
  entry: string
  purpose: string
}

export const PROMPT_USAGE_ITEMS: PromptUsageItem[] = [
  {
    id: 'concept-conversation',
    category: '灵感与蓝图',
    feature: '概念对话',
    stage: 'concept_conversation',
    promptNames: ['concept'],
    status: 'database',
    entry: 'backend/app/api/routers/novels.py',
    purpose: '将用户灵感整理为结构化追问、选项和蓝图准备状态。',
  },
  {
    id: 'world-blueprint',
    category: '灵感与蓝图',
    feature: '世界蓝图生成',
    stage: 'world_blueprint',
    promptNames: ['screenwriting', 'blueprint_json_repair'],
    status: 'database',
    entry: 'backend/app/api/routers/novels.py',
    purpose: '根据概念对话生成世界观、角色关系和章节大纲。',
  },
  {
    id: 'import-analysis',
    category: '导入与抽取',
    feature: '导入小说分析',
    stage: 'import_analysis',
    promptNames: ['import_analysis', 'import_character_filter'],
    status: 'database',
    entry: 'backend/app/services/import_service.py',
    purpose: '从上传文本中提取标题、世界观、角色与章节纲要。',
  },
  {
    id: 'summary-memory',
    category: '导入与抽取',
    feature: '章节摘要记忆',
    stage: 'summary_memory',
    promptNames: ['extraction'],
    status: 'database',
    entry: 'backend/app/services/llm_service.py',
    purpose: '为历史章节生成摘要，供后续写作上下文使用。',
  },
  {
    id: 'chapter-outline',
    category: '章节生产',
    feature: '续写章节大纲',
    stage: 'chapter_outline',
    promptNames: ['outline_generation'],
    status: 'database',
    entry: 'backend/app/api/routers/writer.py',
    purpose: '基于已有蓝图和已有大纲，继续生成后续章节纲要。',
  },
  {
    id: 'chapter-mission',
    category: '章节生产',
    feature: '章节导演脚本',
    stage: 'chapter_mission',
    promptNames: ['chapter_plan'],
    status: 'database',
    entry: 'backend/app/api/routers/writer.py',
    purpose: '把章节大纲转成 POV、节奏、关键事件和允许登场角色。',
  },
  {
    id: 'chapter-writing-1',
    category: '章节生产',
    feature: '候选正文生成 1',
    stage: 'chapter_writing_1',
    promptNames: ['writing_v2'],
    fallbackPromptNames: ['writing'],
    status: 'database',
    entry: 'backend/app/api/routers/writer.py',
    purpose: '结合蓝图、导演脚本、RAG 和历史摘要生成第一份候选正文。',
  },
  {
    id: 'chapter-writing-2',
    category: '章节生产',
    feature: '候选正文生成 2',
    stage: 'chapter_writing_2',
    promptNames: ['writing_v2'],
    fallbackPromptNames: ['writing'],
    status: 'database',
    entry: 'backend/app/api/routers/writer.py',
    purpose: '结合蓝图、导演脚本、RAG 和历史摘要生成第二份候选正文。',
  },
  {
    id: 'chapter-rewrite',
    category: '章节生产',
    feature: '护栏重写',
    stage: 'chapter_rewrite',
    promptNames: ['rewrite_guardrails'],
    status: 'database',
    entry: 'backend/app/api/routers/writer.py',
    purpose: '当正文违反角色可见性或叙事限制时，尝试自动修复。',
  },
  {
    id: 'chapter-enrichment',
    category: '章节生产',
    feature: '章节补写扩展',
    stage: 'chapter_enrichment',
    promptNames: ['chapter_enrichment'],
    status: 'database',
    entry: 'backend/app/api/routers/writer.py',
    purpose: '字数不足时使用内置提示词补写环境、动作、心理和过渡细节。',
  },
  {
    id: 'chapter-compression',
    category: '章节生产',
    feature: '章节压缩',
    stage: 'chapter_compression',
    promptNames: ['chapter_compression'],
    status: 'database',
    entry: 'backend/app/api/routers/writer.py',
    purpose: '字数明显超限时使用内置提示词删减冗余内容。',
  },
  {
    id: 'version-review',
    category: '评审与优化',
    feature: '版本评审',
    stage: 'version_review',
    promptNames: ['editor_review', 'evaluation'],
    status: 'database',
    entry: 'backend/app/services/ai_review_service.py',
    purpose: '评审单版本或多版本章节，给出推荐与修改建议。',
  },
  {
    id: 'chapter-optimization',
    category: '评审与优化',
    feature: '分层优化',
    stage: 'chapter_optimization',
    promptNames: [
      'optimize_dialogue',
      'optimize_environment',
      'optimize_psychology',
      'optimize_rhythm',
      'optimize_recommended_version',
    ],
    status: 'database',
    entry: 'backend/app/api/routers/optimizer.py',
    purpose: '按对话、环境、心理、节奏或评审建议优化章节正文。',
  },
  {
    id: 'foreshadowing',
    category: '分析与治理',
    feature: '伏笔识别与状态判断',
    stage: 'foreshadowing',
    promptNames: ['foreshadowing_candidate_review', 'foreshadowing_status_judge'],
    status: 'database',
    entry: 'backend/app/api/routers/writer.py',
    purpose: '使用内置 JSON 提示词筛选伏笔候选，并判断伏笔推进状态。',
  },
  {
    id: 'foreshadowing-reminder',
    category: '分析与治理',
    feature: '伏笔提醒',
    stage: 'foreshadowing',
    promptNames: ['foreshadowing_reminder'],
    status: 'database',
    entry: 'backend/app/services/foreshadowing_tracker_service.py',
    purpose: '根据章节上下文生成伏笔提醒和处理建议。',
  },
  {
    id: 'emotion-analysis',
    category: '分析与治理',
    feature: 'AI 情绪曲线分析',
    stage: 'emotion_analysis',
    promptNames: ['emotion_analysis'],
    status: 'database',
    entry: 'backend/app/api/routers/analytics.py',
    purpose: '使用内置分析提示词为章节生成情绪类型、强度和叙事阶段。',
  },
  {
    id: 'chapter-preview',
    category: '分析与治理',
    feature: '章节预览链路',
    stage: 'chapter_preview',
    promptNames: ['chapter_preview_generate', 'chapter_preview_evaluate', 'chapter_preview_expand'],
    status: 'database',
    entry: 'backend/app/services/preview_generation_service.py',
    purpose: '使用内置提示词生成、评估并扩写章节预览。',
  },
  {
    id: 'faction-context',
    category: '扩展能力',
    feature: '势力上下文',
    stage: 'chapter_writing_1 / chapter_writing_2',
    promptNames: ['faction_context'],
    status: 'database',
    entry: 'backend/app/services/faction_service.py',
    purpose: '为写作阶段补充阵营、势力与组织关系上下文。',
  },
  {
    id: 'constitution-check',
    category: '扩展能力',
    feature: '设定宪章检查',
    stage: 'consistency_check',
    promptNames: ['constitution_check'],
    status: 'database',
    entry: 'backend/app/services/constitution_service.py',
    purpose: '检查章节是否违反项目设定、角色规则和世界观约束。',
  },
  {
    id: 'six-dimension-review',
    category: '扩展能力',
    feature: '六维评审',
    stage: 'deep_review',
    promptNames: ['six_dimension_review'],
    status: 'database',
    entry: 'backend/app/services/six_dimension_review_service.py',
    purpose: '从多个维度对章节质量做深度评审。',
  },
]
