"""p2_risk_harden_indexes_fk_cascade

Revision ID: 17a89f18291c
Revises: 58f052b1e0fd
Create Date: 2026-07-20 10:31:58.267712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17a89f18291c'
down_revision: Union[str, None] = '58f052b1e0fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_blueprint_characters_project_id'), 'blueprint_characters', ['project_id'], unique=False)
    op.create_index(op.f('ix_blueprint_relationships_project_id'), 'blueprint_relationships', ['project_id'], unique=False)
    op.create_index(op.f('ix_chapter_evaluations_chapter_id'), 'chapter_evaluations', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_chapter_outlines_project_id'), 'chapter_outlines', ['project_id'], unique=False)
    op.create_index(op.f('ix_chapter_versions_chapter_id'), 'chapter_versions', ['chapter_id'], unique=False)
    op.alter_column('foreshadowing_resolutions', 'resolved_at_chapter_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_constraint('foreshadowing_resolutions_resolved_at_chapter_id_fkey', 'foreshadowing_resolutions', type_='foreignkey')
    op.create_foreign_key('foreshadowing_resolutions_resolved_at_chapter_id_fkey', 'foreshadowing_resolutions', 'chapters', ['resolved_at_chapter_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_novel_conversations_project_id'), 'novel_conversations', ['project_id'], unique=False)
    op.alter_column('rag_chunks', 'project_id',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.create_foreign_key('rag_chunks_project_id_fkey', 'rag_chunks', 'novel_projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.alter_column('rag_summaries', 'project_id',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.create_foreign_key('rag_summaries_project_id_fkey', 'rag_summaries', 'novel_projects', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('rag_summaries_project_id_fkey', 'rag_summaries', type_='foreignkey')
    op.alter_column('rag_summaries', 'project_id',
               existing_type=sa.String(length=36),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
    op.drop_constraint('rag_chunks_project_id_fkey', 'rag_chunks', type_='foreignkey')
    op.alter_column('rag_chunks', 'project_id',
               existing_type=sa.String(length=36),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
    op.drop_index(op.f('ix_novel_conversations_project_id'), table_name='novel_conversations')
    op.drop_constraint('foreshadowing_resolutions_resolved_at_chapter_id_fkey', 'foreshadowing_resolutions', type_='foreignkey')
    op.create_foreign_key('foreshadowing_resolutions_resolved_at_chapter_id_fkey', 'foreshadowing_resolutions', 'chapters', ['resolved_at_chapter_id'], ['id'], ondelete='CASCADE')
    op.alter_column('foreshadowing_resolutions', 'resolved_at_chapter_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_index(op.f('ix_chapter_versions_chapter_id'), table_name='chapter_versions')
    op.drop_index(op.f('ix_chapter_outlines_project_id'), table_name='chapter_outlines')
    op.drop_index(op.f('ix_chapter_evaluations_chapter_id'), table_name='chapter_evaluations')
    op.drop_index(op.f('ix_blueprint_relationships_project_id'), table_name='blueprint_relationships')
    op.drop_index(op.f('ix_blueprint_characters_project_id'), table_name='blueprint_characters')
    # ### end Alembic commands ###
