"""add faction constitution writer persona tables

Revision ID: 6e85c84f9541
Revises: 03bb4c218e9e666ec466d0a3
Create Date: 2026-07-19 07:34:48.043845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6e85c84f9541'
down_revision: Union[str, None] = '03bb4c218e9e666ec466d0a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('factions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('faction_type', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=True),
    sa.Column('power_level', sa.String(length=64), nullable=True),
    sa.Column('territory', sa.Text(), nullable=True),
    sa.Column('resources', sa.JSON(), nullable=True),
    sa.Column('leader', sa.String(length=255), nullable=True),
    sa.Column('hierarchy', sa.JSON(), nullable=True),
    sa.Column('member_count', sa.String(length=64), nullable=True),
    sa.Column('goals', sa.JSON(), nullable=True),
    sa.Column('current_status', sa.Text(), nullable=True),
    sa.Column('recent_events', sa.JSON(), nullable=True),
    sa.Column('culture', sa.Text(), nullable=True),
    sa.Column('rules', sa.JSON(), nullable=True),
    sa.Column('traditions', sa.JSON(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['novel_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_factions_project_id'), 'factions', ['project_id'], unique=False)
    op.create_table('novel_constitutions',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('core_theme', sa.String(length=255), nullable=True),
    sa.Column('genre', sa.String(length=128), nullable=True),
    sa.Column('core_conflict', sa.String(length=255), nullable=True),
    sa.Column('story_direction', sa.String(length=255), nullable=True),
    sa.Column('core_values', sa.Text(), nullable=True),
    sa.Column('pov_type', sa.String(length=64), nullable=True),
    sa.Column('pov_character', sa.String(length=255), nullable=True),
    sa.Column('pov_restrictions', sa.Text(), nullable=True),
    sa.Column('target_age_group', sa.String(length=64), nullable=True),
    sa.Column('reading_level', sa.String(length=64), nullable=True),
    sa.Column('violence_rating', sa.String(length=64), nullable=True),
    sa.Column('romance_rating', sa.String(length=64), nullable=True),
    sa.Column('overall_tone', sa.String(length=128), nullable=True),
    sa.Column('realism_level', sa.String(length=128), nullable=True),
    sa.Column('language_style', sa.String(length=128), nullable=True),
    sa.Column('world_type', sa.String(length=128), nullable=True),
    sa.Column('power_system', sa.Text(), nullable=True),
    sa.Column('world_rules', sa.JSON(), nullable=True),
    sa.Column('forbidden_content', sa.JSON(), nullable=True),
    sa.Column('allowed_character_types', sa.JSON(), nullable=True),
    sa.Column('character_power_limits', sa.Text(), nullable=True),
    sa.Column('allowed_relationship_types', sa.JSON(), nullable=True),
    sa.Column('allowed_plot_types', sa.JSON(), nullable=True),
    sa.Column('twist_frequency', sa.String(length=128), nullable=True),
    sa.Column('foreshadowing_rules', sa.Text(), nullable=True),
    sa.Column('time_span', sa.String(length=128), nullable=True),
    sa.Column('geographical_scope', sa.String(length=128), nullable=True),
    sa.Column('time_flow', sa.String(length=128), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['novel_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_table('writer_personas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('identity', sa.Text(), nullable=True),
    sa.Column('experience_years', sa.Integer(), nullable=True),
    sa.Column('expertise_areas', sa.JSON(), nullable=True),
    sa.Column('target_audience', sa.Text(), nullable=True),
    sa.Column('vocabulary_level', sa.String(length=64), nullable=True),
    sa.Column('sentence_rhythm', sa.Text(), nullable=True),
    sa.Column('vocabulary_preferences', sa.JSON(), nullable=True),
    sa.Column('unique_expressions', sa.JSON(), nullable=True),
    sa.Column('formality_level', sa.String(length=64), nullable=True),
    sa.Column('opening_style', sa.Text(), nullable=True),
    sa.Column('transition_style', sa.Text(), nullable=True),
    sa.Column('ending_style', sa.Text(), nullable=True),
    sa.Column('dialogue_style', sa.Text(), nullable=True),
    sa.Column('dialogue_tags', sa.Text(), nullable=True),
    sa.Column('description_style', sa.Text(), nullable=True),
    sa.Column('show_vs_tell_ratio', sa.String(length=64), nullable=True),
    sa.Column('sensory_focus', sa.JSON(), nullable=True),
    sa.Column('catchphrases', sa.JSON(), nullable=True),
    sa.Column('personal_quirks', sa.JSON(), nullable=True),
    sa.Column('imperfection_patterns', sa.JSON(), nullable=True),
    sa.Column('thinking_pauses', sa.JSON(), nullable=True),
    sa.Column('filler_words', sa.JSON(), nullable=True),
    sa.Column('regional_expressions', sa.JSON(), nullable=True),
    sa.Column('avoid_patterns', sa.JSON(), nullable=True),
    sa.Column('variation_rules', sa.JSON(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['novel_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_writer_personas_project_id'), 'writer_personas', ['project_id'], unique=False)
    op.create_table('faction_members',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('faction_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('role', sa.String(length=128), nullable=True),
    sa.Column('rank', sa.String(length=64), nullable=True),
    sa.Column('loyalty', sa.Integer(), nullable=True),
    sa.Column('joined_at', sa.String(length=255), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['blueprint_characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['faction_id'], ['factions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['novel_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_faction_members_project_id'), 'faction_members', ['project_id'], unique=False)
    op.create_table('faction_relationships',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('faction_from_id', sa.Integer(), nullable=False),
    sa.Column('faction_to_id', sa.Integer(), nullable=False),
    sa.Column('relationship_type', sa.String(length=64), nullable=False),
    sa.Column('strength', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('terms', sa.JSON(), nullable=True),
    sa.Column('established_at', sa.String(length=255), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['faction_from_id'], ['factions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['faction_to_id'], ['factions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['novel_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_faction_relationships_project_id'), 'faction_relationships', ['project_id'], unique=False)
    op.create_table('faction_relationship_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('relationship_id', sa.Integer(), nullable=False),
    sa.Column('old_type', sa.String(length=64), nullable=True),
    sa.Column('new_type', sa.String(length=64), nullable=False),
    sa.Column('old_strength', sa.Integer(), nullable=True),
    sa.Column('new_strength', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('chapter_number', sa.Integer(), nullable=True),
    sa.Column('story_time', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['relationship_id'], ['faction_relationships.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('faction_relationship_history')
    op.drop_index(op.f('ix_faction_relationships_project_id'), table_name='faction_relationships')
    op.drop_table('faction_relationships')
    op.drop_index(op.f('ix_faction_members_project_id'), table_name='faction_members')
    op.drop_table('faction_members')
    op.drop_index(op.f('ix_writer_personas_project_id'), table_name='writer_personas')
    op.drop_table('writer_personas')
    op.drop_table('novel_constitutions')
    op.drop_index(op.f('ix_factions_project_id'), table_name='factions')
    op.drop_table('factions')
    # ### end Alembic commands ###
