"""baseline

Revision ID: a53385d06521
Revises: 
Create Date: 2026-07-12 23:49:35.650800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a53385d06521'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('chapter_versions',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('chapter_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('version_label', sa.String(length=64), nullable=True),
    sa.Column('provider', sa.String(length=64), nullable=True),
    sa.Column('content', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chapters',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('chapter_number', sa.Integer(), nullable=False),
    sa.Column('real_summary', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('generation_progress', sa.Integer(), nullable=False),
    sa.Column('generation_step', sa.String(length=64), nullable=True),
    sa.Column('generation_step_index', sa.Integer(), nullable=False),
    sa.Column('generation_step_total', sa.Integer(), nullable=False),
    sa.Column('generation_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('selected_version_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['novel_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['selected_version_id'], ['chapter_versions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'chapter_number', name='uq_chapters_project_number')
    )
    op.create_table('prompts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tags', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompts_name'), 'prompts', ['name'], unique=True)
    op.create_table('system_configs',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('update_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usage_metrics',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('external_id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('blueprint_templates',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('template_type', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chapter_evaluations',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('chapter_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('version_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('decision', sa.String(length=32), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['chapter_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chapter_generation_traces',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('chapter_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('chapter_number', sa.Integer(), nullable=False),
    sa.Column('node_key', sa.String(length=64), nullable=False),
    sa.Column('node_label', sa.String(length=128), nullable=False),
    sa.Column('stage', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('system_prompt', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=True),
    sa.Column('user_prompt', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=True),
    sa.Column('raw_response', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=True),
    sa.Column('cleaned_output', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_chapter_generation_traces_chapter', 'chapter_generation_traces', ['chapter_id', 'node_key'], unique=False)
    op.create_index('idx_chapter_generation_traces_project_chapter', 'chapter_generation_traces', ['project_id', 'chapter_number'], unique=False)
    op.create_table('llm_configs',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('llm_provider_url', sa.Text(), nullable=True),
    sa.Column('llm_provider_api_key', sa.Text(), nullable=True),
    sa.Column('llm_provider_model', sa.Text(), nullable=True),
    sa.Column('embedding_provider_url', sa.Text(), nullable=True),
    sa.Column('embedding_provider_api_key', sa.Text(), nullable=True),
    sa.Column('embedding_provider_model', sa.Text(), nullable=True),
    sa.Column('embedding_provider_format', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('novel_projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('initial_prompt', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_novel_projects_user_id'), 'novel_projects', ['user_id'], unique=False)
    op.create_table('user_model_providers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('provider_type', sa.String(length=32), nullable=False),
    sa.Column('base_url', sa.Text(), nullable=False),
    sa.Column('api_key_encrypted', sa.Text(), nullable=True),
    sa.Column('api_key_preview', sa.String(length=32), nullable=True),
    sa.Column('capabilities_json', sa.JSON(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_model_providers_user_id'), 'user_model_providers', ['user_id'], unique=False)
    op.create_table('background_tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('task_type', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('log_entries', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['novel_projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_background_tasks_project_id'), 'background_tasks', ['project_id'], unique=False)
    op.create_index(op.f('ix_background_tasks_status'), 'background_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_background_tasks_task_type'), 'background_tasks', ['task_type'], unique=False)
    op.create_index(op.f('ix_background_tasks_user_id'), 'background_tasks', ['user_id'], unique=False)
    op.create_table('blueprint_characters',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('identity', sa.String(length=255), nullable=True),
    sa.Column('personality', sa.Text(), nullable=True),
    sa.Column('goals', sa.Text(), nullable=True),
    sa.Column('abilities', sa.Text(), nullable=True),
    sa.Column('relationship_to_protagonist', sa.Text(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['novel_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blueprint_relationships',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('character_from', sa.String(length=255), nullable=False),
    sa.Column('character_to', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['novel_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chapter_blueprints',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('chapter_number', sa.Integer(), nullable=False),
    sa.Column('suspense_density', sa.String(length=32), nullable=True),
    sa.Column('foreshadowing_ops', sa.String(length=128), nullable=True),
    sa.Column('cognitive_twist_level', sa.Integer(), nullable=False),
    sa.Column('chapter_function', sa.String(length=32), nullable=True),
    sa.Column('chapter_focus', sa.String(length=255), nullable=True),
    sa.Column('suspense_type', sa.String(length=128), nullable=True),
    sa.Column('emotional_arc', sa.String(length=255), nullable=True),
    sa.Column('involved_foreshadowings', sa.JSON(), nullable=True),
    sa.Column('mission_constraints', sa.JSON(), nullable=True),
    sa.Column('brief_summary', sa.Text(), nullable=True),
    sa.Column('director_script', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=True),
    sa.Column('beat_sheet', sa.JSON(), nullable=True),
    sa.Column('is_generated', sa.Boolean(), nullable=False),
    sa.Column('is_finalized', sa.Boolean(), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['novel_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chapter_blueprints_chapter_number'), 'chapter_blueprints', ['chapter_number'], unique=False)
    op.create_index(op.f('ix_chapter_blueprints_project_id'), 'chapter_blueprints', ['project_id'], unique=False)
    op.create_table('chapter_outlines',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('chapter_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('goals', sa.Text(), nullable=False),
    sa.Column('highlights', sa.JSON(), nullable=False),
    sa.Column('character_states', sa.JSON(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['novel_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chapter_snapshots',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('chapter_number', sa.Integer(), nullable=False),
    sa.Column('global_summary_snapshot', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=True),
    sa.Column('character_states_snapshot', sa.JSON(), nullable=True),
    sa.Column('plot_arcs_snapshot', sa.JSON(), nullable=True),
    sa.Column('chapter_summary', sa.Text(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['novel_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chapter_snapshots_chapter_number'), 'chapter_snapshots', ['chapter_number'], unique=False)
    op.create_index(op.f('ix_chapter_snapshots_project_id'), 'chapter_snapshots', ['project_id'], unique=False)
    op.create_table('foreshadowing_analysis',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('total_foreshadowings', sa.Integer(), nullable=False),
    sa.Column('resolved_count', sa.Integer(), nullable=False),
    sa.Column('unresolved_count', sa.Integer(), nullable=False),
    sa.Column('abandoned_count', sa.Integer(), nullable=False),
    sa.Column('avg_resolution_distance', sa.Float(), nullable=True),
    sa.Column('unresolved_ratio', sa.Float(), nullable=True),
    sa.Column('pattern_analysis', sa.JSON(), nullable=True),
    sa.Column('overall_quality_score', sa.Float(), nullable=True),
    sa.Column('recommendations', sa.JSON(), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['novel_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_table('foreshadowings',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('chapter_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('chapter_number', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('resolved_chapter_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('resolved_chapter_number', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('target_reveal_chapter', sa.Integer(), nullable=True),
    sa.Column('reveal_method', sa.Text(), nullable=True),
    sa.Column('reveal_impact', sa.Text(), nullable=True),
    sa.Column('related_characters', sa.JSON(), nullable=True),
    sa.Column('related_plots', sa.JSON(), nullable=True),
    sa.Column('related_foreshadowings', sa.JSON(), nullable=True),
    sa.Column('importance', sa.String(length=32), nullable=True),
    sa.Column('urgency', sa.Integer(), nullable=True),
    sa.Column('is_manual', sa.Boolean(), nullable=False),
    sa.Column('ai_confidence', sa.Float(), nullable=True),
    sa.Column('author_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['novel_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_chapter_id'], ['chapters.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_foreshadowings_project_id'), 'foreshadowings', ['project_id'], unique=False)
    op.create_index(op.f('ix_foreshadowings_status'), 'foreshadowings', ['status'], unique=False)
    op.create_table('novel_blueprints',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('target_audience', sa.String(length=255), nullable=True),
    sa.Column('genre', sa.String(length=128), nullable=True),
    sa.Column('style', sa.String(length=128), nullable=True),
    sa.Column('tone', sa.String(length=128), nullable=True),
    sa.Column('one_sentence_summary', sa.Text(), nullable=True),
    sa.Column('full_synopsis', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=True),
    sa.Column('world_setting', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['novel_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_table('novel_conversations',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['novel_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_memories',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('global_summary', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=True),
    sa.Column('plot_arcs', sa.JSON(), nullable=True),
    sa.Column('story_timeline_summary', sa.Text(), nullable=True),
    sa.Column('last_updated_chapter', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['novel_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_memories_project_id'), 'project_memories', ['project_id'], unique=True)
    op.create_table('story_time_trackers',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=255), nullable=False),
    sa.Column('time_system', sa.String(length=64), nullable=True),
    sa.Column('start_date', sa.String(length=64), nullable=True),
    sa.Column('current_date', sa.String(length=64), nullable=True),
    sa.Column('current_time', sa.String(length=64), nullable=True),
    sa.Column('default_chapter_duration', sa.String(length=64), nullable=True),
    sa.Column('chapter_time_map', sa.JSON(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['novel_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_table('timeline_events',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=255), nullable=False),
    sa.Column('chapter_number', sa.Integer(), nullable=False),
    sa.Column('story_time', sa.String(length=255), nullable=True),
    sa.Column('story_date', sa.String(length=64), nullable=True),
    sa.Column('time_elapsed', sa.String(length=128), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=True),
    sa.Column('event_title', sa.String(length=255), nullable=False),
    sa.Column('event_description', sa.Text(), nullable=True),
    sa.Column('involved_characters', sa.JSON(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('caused_by_event_id', sa.BigInteger(), nullable=True),
    sa.Column('leads_to_event_ids', sa.JSON(), nullable=True),
    sa.Column('importance', sa.Integer(), nullable=True),
    sa.Column('is_turning_point', sa.Boolean(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['caused_by_event_id'], ['timeline_events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['novel_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timeline_events_chapter_number'), 'timeline_events', ['chapter_number'], unique=False)
    op.create_index(op.f('ix_timeline_events_project_id'), 'timeline_events', ['project_id'], unique=False)
    op.create_table('user_ai_models',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('model_name', sa.String(length=160), nullable=False),
    sa.Column('capabilities_json', sa.JSON(), nullable=False),
    sa.Column('context_window', sa.Integer(), nullable=True),
    sa.Column('is_default_chat', sa.Boolean(), nullable=False),
    sa.Column('is_default_embedding', sa.Boolean(), nullable=False),
    sa.Column('is_default_tts', sa.Boolean(), nullable=False),
    sa.Column('tts_protocol', sa.String(length=32), nullable=True),
    sa.Column('tts_voice', sa.String(length=120), nullable=True),
    sa.Column('tts_speed', sa.Float(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['user_model_providers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_ai_models_provider_id'), 'user_ai_models', ['provider_id'], unique=False)
    op.create_index(op.f('ix_user_ai_models_user_id'), 'user_ai_models', ['user_id'], unique=False)
    op.create_table('causal_chains',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=255), nullable=False),
    sa.Column('cause_type', sa.String(length=64), nullable=True),
    sa.Column('cause_description', sa.Text(), nullable=False),
    sa.Column('cause_chapter', sa.Integer(), nullable=False),
    sa.Column('effect_type', sa.String(length=64), nullable=True),
    sa.Column('effect_description', sa.Text(), nullable=False),
    sa.Column('effect_chapter', sa.Integer(), nullable=True),
    sa.Column('involved_characters', sa.JSON(), nullable=True),
    sa.Column('cause_event_id', sa.BigInteger(), nullable=True),
    sa.Column('effect_event_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('resolution_description', sa.Text(), nullable=True),
    sa.Column('importance', sa.Integer(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cause_event_id'], ['timeline_events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['effect_event_id'], ['timeline_events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['novel_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_causal_chains_project_id'), 'causal_chains', ['project_id'], unique=False)
    op.create_table('character_states',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=255), nullable=False),
    sa.Column('character_id', sa.BigInteger(), nullable=False),
    sa.Column('character_name', sa.String(length=255), nullable=False),
    sa.Column('chapter_number', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('location_detail', sa.Text(), nullable=True),
    sa.Column('emotion', sa.String(length=64), nullable=True),
    sa.Column('emotion_intensity', sa.Integer(), nullable=True),
    sa.Column('emotion_reason', sa.Text(), nullable=True),
    sa.Column('health_status', sa.String(length=64), nullable=True),
    sa.Column('injuries', sa.JSON(), nullable=True),
    sa.Column('inventory', sa.JSON(), nullable=True),
    sa.Column('inventory_changes', sa.JSON(), nullable=True),
    sa.Column('relationship_changes', sa.JSON(), nullable=True),
    sa.Column('power_level', sa.String(length=64), nullable=True),
    sa.Column('power_changes', sa.JSON(), nullable=True),
    sa.Column('known_secrets', sa.JSON(), nullable=True),
    sa.Column('new_knowledge', sa.JSON(), nullable=True),
    sa.Column('current_goals', sa.JSON(), nullable=True),
    sa.Column('goal_progress', sa.JSON(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['blueprint_characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['novel_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_character_states_chapter_number'), 'character_states', ['chapter_number'], unique=False)
    op.create_index(op.f('ix_character_states_character_id'), 'character_states', ['character_id'], unique=False)
    op.create_index(op.f('ix_character_states_project_id'), 'character_states', ['project_id'], unique=False)
    op.create_table('foreshadowing_reminders',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('foreshadowing_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('reminder_type', sa.String(length=32), nullable=False),
    sa.Column('message', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=False),
    sa.Column('suggested_chapter_range', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('dismissed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dismissed_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['foreshadowing_id'], ['foreshadowings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['novel_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_foreshadowing_reminders_project_id'), 'foreshadowing_reminders', ['project_id'], unique=False)
    op.create_index(op.f('ix_foreshadowing_reminders_status'), 'foreshadowing_reminders', ['status'], unique=False)
    op.create_table('foreshadowing_resolutions',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('foreshadowing_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('resolved_at_chapter_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('resolved_at_chapter_number', sa.Integer(), nullable=False),
    sa.Column('resolution_text', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=False),
    sa.Column('resolution_type', sa.String(length=32), nullable=True),
    sa.Column('quality_score', sa.Integer(), nullable=True),
    sa.Column('reader_satisfaction', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['foreshadowing_id'], ['foreshadowings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_at_chapter_id'], ['chapters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('foreshadowing_status_history',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('foreshadowing_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('old_status', sa.String(length=32), nullable=True),
    sa.Column('new_status', sa.String(length=32), nullable=False),
    sa.Column('chapter_number', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('action_taken', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['foreshadowing_id'], ['foreshadowings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_ai_stage_routes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=64), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['user_ai_models.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'stage')
    )
    op.create_index(op.f('ix_user_ai_stage_routes_model_id'), 'user_ai_stage_routes', ['model_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_ai_stage_routes_model_id'), table_name='user_ai_stage_routes')
    op.drop_table('user_ai_stage_routes')
    op.drop_table('foreshadowing_status_history')
    op.drop_table('foreshadowing_resolutions')
    op.drop_index(op.f('ix_foreshadowing_reminders_status'), table_name='foreshadowing_reminders')
    op.drop_index(op.f('ix_foreshadowing_reminders_project_id'), table_name='foreshadowing_reminders')
    op.drop_table('foreshadowing_reminders')
    op.drop_index(op.f('ix_character_states_project_id'), table_name='character_states')
    op.drop_index(op.f('ix_character_states_character_id'), table_name='character_states')
    op.drop_index(op.f('ix_character_states_chapter_number'), table_name='character_states')
    op.drop_table('character_states')
    op.drop_index(op.f('ix_causal_chains_project_id'), table_name='causal_chains')
    op.drop_table('causal_chains')
    op.drop_index(op.f('ix_user_ai_models_user_id'), table_name='user_ai_models')
    op.drop_index(op.f('ix_user_ai_models_provider_id'), table_name='user_ai_models')
    op.drop_table('user_ai_models')
    op.drop_index(op.f('ix_timeline_events_project_id'), table_name='timeline_events')
    op.drop_index(op.f('ix_timeline_events_chapter_number'), table_name='timeline_events')
    op.drop_table('timeline_events')
    op.drop_table('story_time_trackers')
    op.drop_index(op.f('ix_project_memories_project_id'), table_name='project_memories')
    op.drop_table('project_memories')
    op.drop_table('novel_conversations')
    op.drop_table('novel_blueprints')
    op.drop_index(op.f('ix_foreshadowings_status'), table_name='foreshadowings')
    op.drop_index(op.f('ix_foreshadowings_project_id'), table_name='foreshadowings')
    op.drop_table('foreshadowings')
    op.drop_table('foreshadowing_analysis')
    op.drop_index(op.f('ix_chapter_snapshots_project_id'), table_name='chapter_snapshots')
    op.drop_index(op.f('ix_chapter_snapshots_chapter_number'), table_name='chapter_snapshots')
    op.drop_table('chapter_snapshots')
    op.drop_table('chapter_outlines')
    op.drop_index(op.f('ix_chapter_blueprints_project_id'), table_name='chapter_blueprints')
    op.drop_index(op.f('ix_chapter_blueprints_chapter_number'), table_name='chapter_blueprints')
    op.drop_table('chapter_blueprints')
    op.drop_table('blueprint_relationships')
    op.drop_table('blueprint_characters')
    op.drop_index(op.f('ix_background_tasks_user_id'), table_name='background_tasks')
    op.drop_index(op.f('ix_background_tasks_task_type'), table_name='background_tasks')
    op.drop_index(op.f('ix_background_tasks_status'), table_name='background_tasks')
    op.drop_index(op.f('ix_background_tasks_project_id'), table_name='background_tasks')
    op.drop_table('background_tasks')
    op.drop_index(op.f('ix_user_model_providers_user_id'), table_name='user_model_providers')
    op.drop_table('user_model_providers')
    op.drop_index(op.f('ix_novel_projects_user_id'), table_name='novel_projects')
    op.drop_table('novel_projects')
    op.drop_table('llm_configs')
    op.drop_index('idx_chapter_generation_traces_project_chapter', table_name='chapter_generation_traces')
    op.drop_index('idx_chapter_generation_traces_chapter', table_name='chapter_generation_traces')
    op.drop_table('chapter_generation_traces')
    op.drop_table('chapter_evaluations')
    op.drop_table('blueprint_templates')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('usage_metrics')
    op.drop_table('update_logs')
    op.drop_table('system_configs')
    op.drop_index(op.f('ix_prompts_name'), table_name='prompts')
    op.drop_table('prompts')
    op.drop_table('chapters')
    op.drop_table('chapter_versions')
    op.drop_table('admin_settings')
    # ### end Alembic commands ###
