CREATE TABLE IF NOT EXISTS chapter_generation_traces (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    chapter_id BIGINT NOT NULL,
    project_id VARCHAR(36) NOT NULL,
    chapter_number INT NOT NULL,
    node_key VARCHAR(64) NOT NULL,
    node_label VARCHAR(128) NOT NULL,
    stage VARCHAR(64) NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'success',
    system_prompt LONGTEXT NULL,
    user_prompt LONGTEXT NULL,
    raw_response LONGTEXT NULL,
    cleaned_output LONGTEXT NULL,
    error TEXT NULL,
    metadata JSON NULL,
    started_at TIMESTAMP NULL,
    ended_at TIMESTAMP NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_generation_traces_chapter FOREIGN KEY (chapter_id) REFERENCES chapters(id) ON DELETE CASCADE,
    INDEX idx_chapter_generation_traces_chapter (chapter_id, node_key),
    INDEX idx_chapter_generation_traces_project_chapter (project_id, chapter_number)
);
